Progracqteur\WikipedaleBundle\Entity\Model\Category:
  type: entity
  table: categories
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    label:
      type: string
      length: 255
    used:
      type: boolean
    order:
      type: float
  oneToMany:
    children:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Model\Category
      mappedBy: parent
      orderBy: [ order: asc ]
  manyToOne:
    parent:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Model\Category
      inversedBy: children
      nullable: true
